config/routes.rb
XsezinaCom::Application.routes.draw do
  resources :search

  resources :categories

  resources :friends

  get "admin" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  get "about/index"

  get "board/index"

  resources :posts do
    resources :comments
  end

  root :to => "board#index", :as => "board"

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, :url, :presence => true
  validates :url, :uniqueness => true
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # GET /friends
  # GET /friends.xml
  def index
    @friends = Friend.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.xml
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html { redirect_to friends_url }# show.html.erb
      format.xml  { render :xml => @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.xml
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.xml
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to(@friend, :notice => 'Friend was successfully created.') }
        format.xml  { render :xml => @friend, :status => :created, :location => @friend }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.xml
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to(@friend, :notice => 'Friend was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.xml
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to(friends_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for @friend, :html => {:class => 'well'} do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="hero-unit">
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>
</div>

app/views/friends/index.html.erb
<div class="hero-unit">
<h1>Friends List</h1>
<% @friends.each do |friend| %>
  <div class="well">
    <%= friend.name %>&emsp;&emsp;&emsp;<%= friend.url %>
    <span class="pull-right">
      <%= link_to 'Edit', edit_friend_path(friend) %> | 
      <%= link_to 'Delete', friend, :confirm => 'Are you sure?', :method => :delete %>
    </span>
  </div>
<% end %>
</div>

app/views/friends/new.html.erb
<div class="hero-unit">
  <h1>New friend</h1>

  <%= render 'form' %>

  <%= link_to 'Back', friends_path %>
</div>

app/views/friends/show.html.erb
<div class="hero-unit">
<p id="notice"><%= notice %></p>
<br />

<div class="well">
  <%= @friend.name %>
  <span class="pull-right">
    <%= @friend.url %>
  </span>
</div>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>
</div>