config/routes.rb
XsezinaCom::Application.routes.draw do
  resources :search

  resources :categories

  resources :friends

  get "admin" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  get "about/index"

  get "board/index"

  resources :posts do
    resources :comments
  end

  root :to => "board#index", :as => "board"

end

app/models/category.rb
class Category < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, :body, :presence => true
  belongs_to :post
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  validates :name, :url, :presence => true
  validates :url, :uniqueness => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope :order => 'updated_at DESC, title ASC'
  validates :title, :content, :presence => true

  validates :title, :uniqueness => true

  has_many :comments, :dependent => :destroy
  belongs_to :category

  def self.search(search)
    if search
      search_condition = "%#{search}%"
      find(:all, :conditions => ['title LIKE ? OR tags LIKE ? OR content LIKE ?', 
          search_condition, search_condition, search_condition])
    else
      find(:all)
    end
  end
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  
  validate :password_must_be_present

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "sezina" + salt)
  end

  def password=(password)
    @password = password

    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private
    def password_must_be_present
      errors.add(:password, "Missing password") unless hashed_password.present?
    end

    def generate_salt
      self.salt = self.object_id.to_s + rand.to_s
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  skip_before_filter :authorize
  def index
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  skip_before_filter :authorize
  def index
    @posts = Post.all
    @friends = Friend.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, :only => [:show]
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    begin
      @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Invalid access"
      redirect_to board_url, :notice => "Invalid access"
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @post }
      end
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
    @post.post_time = Time.now

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
    @post.post_time = Time.now

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      :autolink => true,
      :space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :hard_wrap => true,
      :strikethrough => true,
      :gh_blockcode => true
    }

    markdown = Redcarpet::Markdown.new(HTMLwithCodeRay, options)
    markdown.render(h(text)).html_safe
  end

  class HTMLwithCodeRay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div(:tab_width => 2)
    end
  end
=begin
  def markdown(text)
    options = {
      :autolink => true,
      :space_after_headers => true,
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :hard_wrap => true,
      :strikethrough => true,
      :gh_blockcode => true
    }
    #options = [:hard_wrap, :filter_html, :auotlink, :no_intra_emphasis, :fenced_code, :gh_blockcode]
    syntax_highlighter(Redcarpet::Markdown.new(text, options).to_html).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
=end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="hero-unit">
  <%= button_to 'Posts list', posts_path, :method => :get, 
    :class => 'btn btn-primary btn-large' %>
  <%= button_to 'New post', new_post_path, :method => :get,
    :class => 'btn btn-primary btn-large' %>
  <%= button_to 'Logout', logout_path, :method => :delete,
    :class => 'btn btn-primary btn-large' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>xSezina.com</title>
  <%= stylesheet_link_tag '../bootstrap/css/bootstrap.css'%>
  <%= stylesheet_link_tag '../bootstrap/css/bootstrap-responsive.css'%>
  <%= stylesheet_link_tag '../bootstrap/css/docs.css'%>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.7.2.min.js'%>
  <%= javascript_include_tag '../bootstrap/js/bootstrap.min.js'%>
  <%= javascript_include_tag '../bootstrap/js/bootstrap-collapse.js' %>
  <%= javascript_include_tag '../bootstrap/js/bootstrap-dropdown.js'%> 
  <%= javascript_include_tag 'prototype.js' %>
  <%= javascript_include_tag 'effects.js' %>
  <%= javascript_include_tag 'controls.js' %>
  <%= javascript_include_tag 'rails.js'%>
  <%= javascript_include_tag 'application.js' %>
  <%= javascript_include_tag '../bootstrap/js/application.js'%>
  <%= javascript_include_tag '../bootstrap/js/bootstrap-dropdown.js' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" type="button">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'xSezina.com', '/', html_options = {:class => "brand"} %>
        <div class="nav-collapse collapse" style="height: 0px;">
          <ul class="nav">
            <li class=""><%= link_to 'Home', '/' %></li>
            <li class="divider-vertical"></li>
            <li class=""><%= link_to 'About', :controller => 'about', :action => 'index' %></li>
            <% if session[:user_id] %>
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <%= link_to 'Admin', '#', 
                  html_options = {:class => 'dropdown-toggle', 
                    "data-toggle" => "dropdown"
                    } %>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Posts List', posts_path %></li>
                  <li><%= link_to 'New Post', new_post_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Categories List', categories_path %></li>
                  <li><%= link_to 'New Category', new_category_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Friends List', friends_path %></li>
                  <li><%= link_to 'New Friend', new_friend_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Logout', logout_path, :method => :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>
          <%= form_tag search_index_path, :method => :get, :class => 'navbar-search pull-right' do %>
            <%= text_field_tag :search, params[:search], :class => 'span2', :placeholder => "search" %>
            <%= submit_tag "Search", :name => nil, :style => 'display: none;' %>
          <% end %>
          <!--
          <form class="navbar-search pull-right" action="http://www.google.com/search">
            <input type="hidden" name="as_sitesearch" value="xsezina.com" />
            <input class="search-query span2" type="text" name="as_q" placeholder="Search" />
            <button type="submit" class="btn" style="display: none;">Search</button>
          </form>
          -->
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span7">
        <%= yield %>
      </div>
      <div class="span3">
        <div class="hero-unit">
          <h2>Categories</h2>
          <ul>
            <% Category.all.each do |category| %>
              <li>
                <%= link_to category.title, category %>
                <span>
                  (<%= category.posts.count %>)
                </span>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="hero-unit">
          <h2>Friends</h2>
          <ul>
            <% Friend.all.each do |friend| %>
              <li>
                <%= link_to friend.name, friend.url %>
              </li>
            <% end %>
            <li>
              <%= link_to'sezina的知识库', 'http://blog.csdn.net/sezinaZero' %>
              曾经用过的博客，里面仅有两篇有关Arch Linux安装的文章。
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="footer">
      <span>
        Powered by Rails3.0.7 &amp; Bootstrap 2.0.4
      </span>
      <br />
      <span>
        Copyright&copy;2012~ sezina.
      </span>
    </div>
  </div>
</body>
</html>