config/routes.rb
XsezinaCom::Application.routes.draw do
  resources :search

  resources :categories

  resources :friends

  get "admin" => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  get "about/index"

  get "board/index"

  resources :posts do
    resources :comments
  end

  root :to => "board#index", :as => "board"

end

app/models/category.rb
class Category < ActiveRecord::Base
  default_scope :order => 'title'
  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_filter :authorize, :only => [:show]
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(categories_url, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(categories_url, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:class => 'well'} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="hero-unit">
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="hero-unit">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
  <h1>Listing categories</h1>
  
  <% @categories.each do |category| %>
    <div class="well">
      <h3 class="pull-left"><%= category.title %></h3>
      <span class="pull-right">
        <%= link_to 'Edit', edit_category_path(category) %>
        <%= link_to 'Delete', category, :confirm => 'Are you sure?', :method => :delete %>
      </span>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="hero-unit">
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<% @category.posts.each do |post| %>
  <div class="hero-unit">
    <div class="post">
      <div class="post-head">
        <h1><%= link_to post.title, post %></h1>
        <span class="pull-left">
          <i class="icon-time"></i>
          <%= post.post_time.strftime('%Y-%m-%d') %>&nbsp;&nbsp;&nbsp;
          <i class="icon-tag"></i>
          <%= @category.title %>&nbsp;&nbsp;&nbsp;
          <i class="icon-comment"></i>
          <%= post.comments.count %> comments
        </span>
        <br />
      </div>

      <div class="lead">
        <%= raw markdown(post.content) %>
      </div>
    </div>
  </div>
<% end %>